//  obloco try catch vai tentar executar um c처dico caso n찾o consiga.
// ele pode retorna o erro que esse c처dico gerou
// ele n찾o para a funcion


// let b = 2;

try {

    let a = 2 + b;

} catch (erro) {
    console.log(erro);

}

console.log("teste");
